nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:5173", "http://127.0.0.1:5173"]
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    max_age: 3600
    allow_credentials: true
  paths:
    "^/api/":
      allow_origin: ["http://localhost:5173", "http://127.0.0.1:5173"]
      allow_methods: ["GET", "POST", "PUT", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
      allow_credentials: true
